<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Setting Eligibility</name>
  <uuid>955b425b-6f81-476b-85e5-b9deec9361ad</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Check MHRSD Parents Employment Status' is "Set Partial Eligible"
then
	set decision to "Partial Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
