<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>MHRSD Parent gov or none</name>
  <uuid>2e12b123-8995-479a-893b-14e3bc421875</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'MHRSD Parents Employment Status' is "Both in Government or None"
	and 'Decision 10' is "Check MHRSD Parents Employment Status"
then
	set decision to "Full Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
