<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Checking MHRSD Parents Employment Status</name>
  <uuid>923702dd-dd06-49b0-978d-a5bf4c804fd9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'MHRSD Parents Employment Status' is "One or More Private"
then
	set decision to "Set Partial Eligible" ;

else 
	set decision to "Set Full Eligible" ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
