<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>PHI Validation for more than 25 years for single</name>
  <uuid>90239854-1c0b-4d00-9a74-d85b8094e72d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	MOI is "Single" and Age is less than 25 
then
	set decision to "Check CCHI PHI Validation" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
