<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Eligibility for less than 25 and single</name>
  <uuid>4dd43ad1-bffd-4951-bb63-fabd083035ea</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'CCHI PHI Validation for less than 25' is true
then
	set decision to "Partial Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
