<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Checking MHRSD Employment Status</name>
  <uuid>039b807f-cd93-4ad7-b313-808c26217fed</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'MHRSD Employment Status' is "Private"
	and 'CCHI PHI Validation more than 25 for single' is "Check MHRSD Employment Status"
then
	set decision to "Set Partial Eligible" ;

else 
	set decision to "Check Gender" ; 

    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
