<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Checking MHRSD Parents Employment Status </name>
  <uuid>611b50c6-a3f8-4767-b5a5-49c30dfa0e3d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'MHRSD Parents Employment Status Single Less than 25' is "Set Full Eligible"
then
	set decision to "Set Full Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
