<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Setting Eligibility</name>
  <uuid>29a2e808-97e5-48ea-89d2-73ef28b0f978</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Check MHRSD Parents Employment Status' is "Set Full Eligible"
then
	set decision to "Full Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
