<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Married</name>
  <uuid>eae31180-abc5-4ffa-b727-451fe5510897</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Marital Status' is "Married"
then
	set decision to "Check MHRSD Employment Status" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
