<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check MHRSD Parent Employment Status One or More</name>
  <uuid>dcae7fcc-e3c1-4d99-b4e1-927598166e96</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'MHRSD Parents Employment Status' is "One or More in Private"
	and 'Decision 9' is "Check MHRSD Parents Employment Status"
then
	set decision to "Partial Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
