<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check MHRSD Emp Status Gov or None Male</name>
  <uuid>7d69db6d-48d5-4584-8fdc-e454f97b0124</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'MHRSD Employment Status' is "Government or None"
	and 'Decision 9' is "Check MHRSD Employment Status"
    and 'Gender' is "Male" 
then
	set decision to "Full Eligible";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
