<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check MHRSD Emp Status Private</name>
  <uuid>ce752b58-5719-44ab-8e29-a0cc270f0fd0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'MHRSD Employment Status' is "Private"
	and 'Decision 9' is "Check MHRSD Employment Status"
then
	set decision to "Partial Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
