<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>CCHI PHI Validation Check</name>
  <uuid>5af625d8-3670-4f72-90bb-f5853f85f7c1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'CCHI PHI Validation for less than 25' is false
then
	set decision to "MHRSD Parents Employment Status" ;
    
    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
