<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Setting Eligibility</name>
  <uuid>1c19e0e7-ef55-496f-937b-5023d584d875</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Government Or None' is "Set Full Eligible"
then
	set decision to "Full Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
