<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Checking MHRSD Employment Status</name>
  <uuid>8b4eac71-f57b-4223-a409-7f65a6506d09</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'MHRSD Employment Status' is "Government Or None"
then
	set decision to "Set Full Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
