<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>CCHI PHI Validation Check</name>
  <uuid>e5e0934a-d23b-4876-90c0-a3e583f1dbaf</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Less than 25 for single' is "Check CCHI PHI Validation" and 'CCHI PHI Validation' is true 
then
	set decision to "Set Partial Eligible" ;

else 
	set decision to "Check MHRSD Parents Employment Status" ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
