<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Partial Eligibility Check</name>
  <uuid>5769b622-886a-4a86-b8a1-f778e2e0c561</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Decision 11' is "Partial Eligible"
	or 'Decision 9' is "Partial Eligible"
	or 'Decision 10' is "Partial Eligible"
then
	set decision to "Partial Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
