<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Married BR</name>
  <uuid>83d2bea6-c7f3-419b-97e1-ca16d8d1de15</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	MOI is "Married"
then
	set decision to "Check MHRSD Employment Status" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
