<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Checking MHRSD Employment Status</name>
  <uuid>db72ff50-b676-4509-bc19-44bc2ecd25bc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'MHRSD Employment Status more than 25' is "Set Partial Eligible"
then
	set decision to "Set Partial Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
