<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Eligibility for PHI YES more than 25</name>
  <uuid>365dcda9-386f-4480-a72b-8cf35e66de27</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'CCHI PHI Validation for more than 25' is true 
then
	set decision to "Partial Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
