<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>saadada</name>
  <uuid>dd4eb969-168a-4aa7-8d84-e325a76f2645</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Private is "Set Partial Eligible"
then
	set decision to "Partial Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
