<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Checking CCHI PHI Validation</name>
  <uuid>3c37ea07-0d70-474d-9b94-9bceeecbffb2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'CCHI PHI Validation' is true
then
	set decision to true ;
else 
	set decision to false ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
