<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Checking MHRSD Parents Employment Status</name>
  <uuid>84680a65-b43d-41f8-a890-a16d115d3296</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'MHRSD Parents Employment Status Single Less than 25' is "Set Partial Eligible"
then
	set decision to "Set Partial Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
