<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>CCHI No and at most 25</name>
  <uuid>5ecfcecd-9ff9-42d3-803b-08face08ac57</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Decision 7' is "Check CCHI PHI Validation"
	and 'CCHI PHI Validation' is "No"
    and Age is at most 25 
then
	set decision to "Check MHRSD Parents Employment Status" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
