<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>CCHI Yes</name>
  <uuid>93e6eea1-385d-4374-aa73-d15f90d853d6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Decision 7' is "Check CCHI PHI Validation"
	and 'CCHI PHI Validation' is "Yes"
then
	set decision to "Partial Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
