<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>CCHI No and more than 25</name>
  <uuid>f01c04b2-bd18-4b37-b8aa-ff6aa21c2962</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Decision 7' is "Check CCHI PHI Validation"
	and 'CCHI PHI Validation' is "No"
    and Age is more than 25 
then
	set decision to "Check MHRSD Employment Status" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
