<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Married and emp Status one or more</name>
  <uuid>da82a037-34de-460d-be79-af8b0a307cde</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Decision 7' is "Check MHRSD Employment Status"
	and 'MHRSD Employment Status' is "One or More in Private"
then
	set decision to "Partial Eligible" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
