<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Marital Status</name>
  <uuid>197013ab-d6e5-4c6e-bfcd-84c8d1c5c9d9</uuid>
  <documentation><![CDATA[to check marital status]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Marital Status' is "Married" 
then
	set decision to "Married" ;
else
	set decision to "Single";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
