<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name> Checking CCHI PHI Validation</name>
  <uuid>8c8706af-aa46-4f68-8e9e-37075d0b3984</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'CCHI PHI Validation' is true
then
	set decision to true ;
else 
	set decision to false ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
